### ISSUE TITLE
感谢提供方案，顺便求字体

### ISSUE THREAD

**Issue by Breeze-WQ** [ASC8384/myRime#2]
这是我目前用下来最舒服的双拼方案，非常感谢。但是在用\fh输入符合时，很多符号都是显示为方块，请问怎么处理？是修改字体吗？你使用的字体能分享下吗？

**Comment by ASC8384** [comment]
在 [此处](https://github.com/ASC8384/myRime/blob/master/weasel.custom.yaml) 有说明

思源黑体
