### ISSUE TITLE
很好用 但是不知道我的小鹤双拼里面有繁体 

### ISSUE THREAD

**Issue by lisansas** [ASC8384/myRime#3]
是我的问题吗？还是说需要关闭什么？
![Clip_20210810_172520](https://user-images.githubusercontent.com/38862056/128842835-8c676ade-bc3c-4542-95db-ca88e9122964.png)

**Comment by lisansas** [comment]
原来也要关闭 我开了ditto快捷键按不出来

**Comment by lisansas** [comment]
但我又发现一个问题 翻页键总是坏掉 比如打vssi 翻页点两下就变成了螽斯= 之后按所有的翻页键都是这样= 或者这样-

**Comment by ASC8384** [comment]
> 
> 
> 但我又发现一个问题 翻页键总是坏掉 比如打vssi 翻页点两下就变成了螽斯= 之后按所有的翻页键都是这样= 或者这样-

非常抱歉这么晚才看到您的问题。
能具体说说下面这个描述吗？譬如截图
> 翻页点两下就变成了螽斯= 之后按所有的翻页键都是这样= 或者这样-

**Comment by lisansas** [comment]
> > 但我又发现一个问题 翻页键总是坏掉 比如打vssi 翻页点两下就变成了螽斯= 之后按所有的翻页键都是这样= 或者这样-
> 
> 非常抱歉这么晚才看到您的问题。
> 能具体说说下面这个描述吗？譬如截图
> 
> > 翻页点两下就变成了螽斯= 之后按所有的翻页键都是这样= 或者这样-

不用了 我已经完全解决了 这个问题在于Windows版本rime词库与mac有一点区别 如果直接用某个python的搜狗细胞词库转rime词库脚本会出现一些问题  比如我这个打字的问题 

再用深蓝词库转换进行一次词库修复就好了

谢谢你热心的回复 我仍在用大佬你的配置 相当好用
